apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
spec:
  containers:
  - name: webapp-color
    image: webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: pink