apiVersion: v1
kind: Pod
metadata: 
  name: simple-webapp
  labels:
    name: App1
    function: Database
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports:
      - containerPort: 8080
